### ISSUE TITLE
"Browse Class" results in empty System Browser

### ISSUE THREAD

**Issue by baderth** [jgfoster/Jade.bak#109]
#107 

This is where I end up when using "Browse Class" from method search (empty System browser poiting at "Packages"):
![image](https://user-images.githubusercontent.com/1823917/28153493-fd6174b8-67a5-11e7-98eb-11526e96a20b.png)

**Comment by jgfoster** [comment]
To test this I tried Jade 2.1.11 on the client and GemStone 3.3.6 on the server. I used a base GLASS image (extent0.seaside.dbf) and browsed implementers of asAnnouncement (there are six of them). I selected each one in turn and it opened a browser on the class and method, but the Dictionaries side not the Packages side. Are you able to reproduce the problem on a method on a System class in Globals (say, Array)? Can you provide any further details? If not, then would you be willing to try out a debug version?

**Comment by baderth** [comment]
2.1.11 / 3.3.3 here.
Searching for "isArray" and rightclick "browse class" or double clicking the method on the Array class results in:
![image](https://user-images.githubusercontent.com/1823917/28201092-b5f8836c-686f-11e7-9d31-53ceadc543a8.png)

Seems like there is some kind of problem in the sequence of the system browser startup, its where it should be for a fraction of a second and then ends up where the screenshot is taken from.
(ending up in packages oder dictionaries isnt really reproduceable, first i thought it puts me where the source system browser, where i searched for implementors was, but thats no always the case)

landing on the right spot was an issue in earlier versions too, but it worked more often than not. iirc problems happened with a bunch of windows open, so thats why its my guess earlier was that it is some problem with the initialization sequence.

if that doesnt help, for sure i'm willing to try a debug version, where can i get it?

**Comment by jgfoster** [comment]
@baderth, I apologize for letting this drag out for so long. I'm back to a point where I have a bit of time to look at Jade issues and was wondering if you are still having this problem. If so, then I'd like to work with you on it. Thanks!

**Comment by jgfoster** [comment]
Sorry, that was supposed to be "Comment", not "Close and Comment"!

**Comment by baderth** [comment]
@jgfoster Yep, "problem" still exists, but its a minor one.
Its still reproducible as I stated in my comment from 14 Jul 2017.
Please advice me if i can support in any investigations.

**Comment by jgfoster** [comment]
@baderth I've added a "Debug" option to the Preferences window (available from the Transcript). Please turn that on, try the steps again, then turn it off (to avoid growing a large log) and send me the Jade.log privately (James.Foster at my company). Thanks!

**Comment by baderth** [comment]
Confirm fixed in 2.2.6, thanks.

**Comment by bloigge** [comment]
Hi (I am a colleague of thomas and gerhard). 

I am still seeing this problem (Jade 2.2.6 Gemstone 3.4.0). In an external window (e.g after searching for method implementors) when I double-click  the class or make a right-click and "Browse Class" a new system browser opens, the selected class shows up for less than a second and disappears. In the end I am back on an empty system browser.

IMHO the best implementation would be that the selected class would open in the existing class browser (if that would be possible).

BTW, thank you for the great work!

**Comment by jgfoster** [comment]
@bloigge, Thanks for the report. I'll take a look.

**Comment by jgfoster** [comment]
@bloigge, I'm reviewing some older items and it looks like I tried another fix. Have you seen this issue recently?

**Comment by jgfoster** [comment]
Looks like no activity for a couple years, so I'll close for now.
